### PR TITLE
fix(git config): do not override global git settings

### PR DESCRIPTION
**Pull request by SomeKittens**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks good to me! One thing I'd appreciate is to update the tests on [this line](https://github.com/SomeKittens/publish-latest/blob/master/src/index.test.js#L21) and [this line](https://github.com/SomeKittens/publish-latest/blob/master/src/index.test.js#L42).

**Comment by SomeKittens** [comment]
Tests updated!

**Comment by kentcdodds** [comment]
Thanks! I rebased and merged this using rebase-and-merge and I guess your branch wasn't rebased. This is in!

**Comment by kentcdodds** [comment]
Hey @SomeKittens, looks like this actually breaks publish-latest :-( as seen in [this build](https://travis-ci.org/formly-js/angular-formly/builds/84583040)

I'm going to have to revert this.

**Comment by kentcdodds** [comment]
Haven't reverted it, just deprecated the last version. I'll open an issue to figure out what the problem was.

**Pull request closed without merging**
